version: '3'
services:
  v2ray:
    image: v2fly/v2fly-core
    container_name: vmon_v2ray
    restart: always
    network_mode: host
    environment:
      - V2RAY_VMESS_AEAD_FORCED=false
    volumes:
        - ./config.json:/etc/v2ray/config.json:ro
